[WIP] feat: Expose underlying k8s resource status to coe cluster status reason
vexxhost/magnum-cluster-api pull request #122
Opened 2023-06-07 15:08 UTC by okozachenko1203

2023-06-19 17:21 UTC, mnaser requested changes
I think there's some ways we can clean this up in the first round of review.

2023-06-19 17:21 UTC, mnaser commented on magnum_cluster_api/driver.py
> +                cluster.save()
since this code is repeated, does it make sense to refactor this to a function called `_update_cluster_status` or something along those lines?

2023-06-19 17:21 UTC, mnaser commented on magnum_cluster_api/resources.py
> +    )
This code seems to be common, I have a thought

https://github.com/vexxhost/magnum-cluster-api/blob/main/magnum_cluster_api/objects.py

What if we created a class based off `pykube.objects.NamespacedAPIObject` which exposed a function like this:

```python
@property
def events(self):
  pass
```

Since the object already has the version, kind, name and namespace.  We can use that to retrieve all events for any object.

2023-06-20 16:05 UTC, okozachenko1203 commented
> I think there's some ways we can clean this up in the first round of review.

@mnaser all comments resolved now

2023-06-27 15:09 UTC, merged