Add support for boot_volume_{size,type}
vexxhost/magnum-cluster-api pull request #13
Opened 2022-10-27 06:27 UTC by okozachenko1203

Fix #5

2022-10-27 09:34 UTC, okozachenko1203 commented
test

2022-10-27 12:28 UTC, mnaser requested changes
@okozachenko1203 I think this breaks the use case if no volume size is set/enabled. 

Would it make more sense to instead have an if statement like I did for audit ?

2022-10-27 13:53 UTC, mnaser commented
```
Oct 27 13:52:48 devstack-magnum magnum-conductor[1094359]: ERROR oslo_messaging.rpc.server     if boot_volume_size > 0:
Oct 27 13:52:48 devstack-magnum magnum-conductor[1094359]: ERROR oslo_messaging.rpc.server TypeError: '>' not supported between instances of 'str' and 'int'
```

2022-10-27 13:55 UTC, mnaser requested changes

2022-10-27 13:55 UTC, mnaser commented on magnum_cluster_api/resources.py
> +        boot_volume_size = get_label_value(
let's refactor this to get_int_label_value which parses the value into an in (similar to `get_bool_label_value`)

2022-10-27 21:09 UTC, mnaser requested changes
I think it would be really good if you tested this in your environment.

2022-10-27 21:09 UTC, mnaser commented on magnum_cluster_api/resources.py
> +                    cinder.get_default_boot_volume_type(self.context),
```
AttributeError: 'OpenStackMachineTemplate' object has no attribute 'context'
```

2022-11-01 17:15 UTC, mnaser approved these changes

2022-11-01 17:15 UTC, merged