feat: support keystone-auth
vexxhost/magnum-cluster-api pull request #297
Opened 2024-01-22 12:48 UTC by okozachenko1203

2024-01-23 14:45 UTC, okozachenko1203 commented
This has been tested on local lab

2024-02-09 19:58 UTC, mnaser requested changes
I think we can take this as an opportunity to start cleaning up all of our manifests which are bundled.  I think it's very difficult to manage them at the moment and I would like to suggest the following:

1. Create a `charts` folder and start bundling the charts in there, if there is no chart, we build it (in this case for this)
2. Since we already have Helm on the system, we can simply use `helm template` with a custom values file instead of using Jinja2
3. With that in place, we're able to simply just bump the chart data in here and easily change the overrides by relying on `values` instead of raw manifest files.
4. The templated value is what we "feed" into the ClusterResourceSet, and it also makes it easier for the long run to transition to the addon providers as well since we will have the charts ahead of time.

Can you make changes to this to accomodate for that?

2024-02-15 21:07 UTC, mnaser commented
@okozachenko1203: this assumes that `magnum-conductor` can reach the cluster directly.  In Atmosphere, it can. However, when users are using OSA or Kolla, that is likely not the case, so we'll have to rely on CAPO for the cluster to be reachable (especially in scenarios when the cluster proxy is running).

2024-02-26 15:59 UTC, mnaser requested changes

2024-02-26 15:59 UTC, mnaser commented on magnum_cluster_api/resources.py
> +                                ),
refactor into helm chart value

2024-02-26 15:59 UTC, mnaser commented on magnum_cluster_api/resources.py
> +                            },
move logic to helm chart

2024-02-26 15:59 UTC, mnaser commented on magnum_cluster_api/utils.py
> +def get_keystone_auth_default_policy(cluster: magnum_objects.Cluster):
lets make this return a dicft

2024-02-28 16:33 UTC, mnaser approved these changes

2024-02-28 16:34 UTC, merged